### ISSUE TITLE
TypeError in ntlm internals

### ISSUE THREAD

**Issue by ad34** [Node-SMB/ntlm#5]
Trying to use this module, I get a TypeError inside the library with the following callstack

>node app.js

mypath\node_modules\ntlm\lib\ntlm.js:229
  var serverNonce = new Buffer((res.headers['www-authenticate'].match(/^NTLM\s+(.+?)(,|\s+|$)/) || [])[1], 'base64');
                                    ^

TypeError: Cannot read property 'headers' of undefined
    at Object.exports.responseHeader (node_modules\ntlm\lib\ntlm.js:229:37)
    at Request._callback (\app.js:26:31)
    at self.callback (node_modules\request\request.js:185:22)
    at Request.emit (events.js:210:5)
    at Request.start (node_modules\request\request.js:753:10)
    at Request.end node_modules\request\request.js:1511:10)
    at end (node_modules\request\request.js:564:14)
    at Immediate.<anonymous> (node_modules\request\request.js:578:7)
    at processImmediate (internal/timers.js:439:21)

**Comment by ad34** [comment]
res was null due to self signed certificate in the chain , issue is fixed however checking the value of res before accessing the header would avoid the TypeError
